version: '2'

services:
    workpackage:
      build: 
        context: .
        dockerfile: ${MS_WORKPACKAGE_HOME}/dev/Dockerfile.dev
        args:
            DEV_HOME : ${MS_WORKPACKAGE_HOME}

      container_name: workpackage_cn
      ports:
        - "8080:8080"

      volumes:
         - ../ms-workpackage:${MS_WORKPACKAGE_HOME}

      external_links:
        - postgresdb:postgres
      networks:
        - default
        - postgresdb_default

    task:
       build:
         context: .
         dockerfile: ${MS_TASK_HOME}/dev/Dockerfile.dev
         args:
             DEV_HOME : ${MS_TASK_HOME}
       container_name: task_cn

       ports:
         - "8079:8080"

       volumes:
          - ../ms-task:${MS_TASK_HOME}

       external_links:
         - postgresdb:postgres
       networks:
         - default
         - postgresdb_default

networks:
    default:
    postgresdb_default:
      external: true

volumes:
  dbdata: