version: '2'

services:
    tools:
      build: 
        context: .
        dockerfile: ${MS_TOOL_HOME}/dev/Dockerfile.dev
        args:
            DEV_HOME : ${MS_TOOL_HOME}

      container_name: tool_cn
      ports:
        - "8078:8080"

      volumes:
         - ../ms-tool:${MS_TOOL_HOME}

      external_links:
        - postgresdb:postgres
      networks:
        - default
        - postgresdb_default

networks:
    default:
    postgresdb_default:
      external: true

volumes:
  dbdata: