INSERT INTO public.REST_DB_TASKS(ID,NAME) VALUES (1,'TASK1');
INSERT INTO public.REST_DB_TASKS(ID,NAME) VALUES (2,'TASK2');
INSERT INTO public.REST_DB_TASKS(ID,NAME) VALUES (3,'TASK3');
INSERT INTO public.REST_DB_TASKS(ID,NAME) VALUES (4,'TASK4');

