INSERT INTO public.REST_DB_TOOLS(ID,NAME) VALUES (1,'TOOL1');
INSERT INTO public.REST_DB_TOOLS(ID,NAME) VALUES (2,'TOOL2');
INSERT INTO public.REST_DB_TOOLS(ID,NAME) VALUES (3,'TOOL3');
INSERT INTO public.REST_DB_TOOLS(ID,NAME) VALUES (4,'TOOL4');

