INSERT INTO public.REST_DB_TOOLS(TOOL_ID,TASK_ID,TOOL_NAME) VALUES (1,2,'TOOL1');
INSERT INTO public.REST_DB_TOOLS(TOOL_ID,TASK_ID,TOOL_NAME) VALUES (2,3,'TOOL2');
INSERT INTO public.REST_DB_TOOLS(TOOL_ID,TASK_ID,TOOL_NAME) VALUES (3,3,'TOOL3');
INSERT INTO public.REST_DB_TOOLS(TOOL_ID,TASK_ID,TOOL_NAME) VALUES (4,1,'TOOL4');

