INSERT INTO public.REST_DB_WORKPACKAGE(ID, BARCODE,NAME) VALUES (1,'BC1', 'WP1');
INSERT INTO public.REST_DB_WORKPACKAGE(ID, BARCODE,NAME) VALUES (2,'BC2', 'WP2');
INSERT INTO public.REST_DB_WORKPACKAGE(ID, BARCODE,NAME) VALUES (3,'BC3', 'WP3');
INSERT INTO public.REST_DB_WORKPACKAGE(ID, BARCODE,NAME) VALUES (4,'BC4', 'WP4');

